name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Typecheck
        run: bunx tsc --noEmit

      - name: Lint
        run: bun lint
